name: weather_watch
description: "An app to show your current location weather"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE

  # Icons
  phosphor_flutter: ^2.1.0
  cupertino_icons: ^1.0.6

  #Fonts
  google_fonts: ^6.2.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  flutter_svg: ^2.0.11
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  toastification: ^2.3.0
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FEE3BC"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/weathers/
    - assets/icons/